export const RECEIVE_USER_ID = 'RECEIVE_USER_ID';
export const RECEIVE_SESSION_ID = 'RECEIVE_SESSION_ID';
export const RECEIVE_PUZZLES = 'RECEIVE_PUZZLES';

export const SET_OPTION_SHOWTIMER = 'SET_OPTION_SHOWTIMER';
export const SET_OPTION_TIMERTRIGGER = 'SET_OPTION_TIMERTRIGGER';

export const SET_ACTIVE_VIEW = 'SET_ACTIVE_VIEW';

export const RECEIVE_ACTIVE_PUZZLE = 'RECEIVE_ACTIVE_PUZZLE';

export const RECEIVE_SCRAMBLE = 'RECEIVE_SCRAMBLE';

export const CLEAR_SOLVES = 'CLEAR_SOLVES';
export const ADD_SOLVE = 'ADD_SOLVE';
export const UPDATE_SOLVE = 'UPDATE_SOLVE';
export const DELETE_SOLVE = 'DELETE_SOLVE';

export const RECEIVE_STATS = 'RECEIVE_STATS';