export const RECEIVE_USER_ID = 'RECEIVE_USER_ID';
export const RECEIVE_PUZZLES = 'RECEIVE_PUZZLES';

export const SET_OPTION_SHOWTIMER = 'SET_OPTION_SHOWTIMER';
export const SET_OPTION_TIMERTRIGGER = 'SET_OPTION_TIMERTRIGGER';

export const SET_ACTIVE_VIEW = 'SET_ACTIVE_VIEW';

export const SET_ACTIVE_PUZZLE = 'SET_ACTIVE_PUZZLE';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';


export const ADD_SOLVE = 'ADD_SOLVE';
export const SET_TIMER_START = 'SET_TIMER_START';
export const SET_TIMER_LABEL = 'SET_TIMER_LABEL';