name: Deploy main branch to production site

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Install, test, and build"
        run: |
          npm ci
          npm run test
          npm run build
        env:
          CI: true
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}"
          projectId: aetherium-3cedf
          channelId: live
